CREATE TABLE TEST.DOC (
  ID   SERIAL PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE TEST.WORD (
  ID     SERIAL PRIMARY KEY,
  WORD   VARCHAR NOT NULL,
  DOC_ID BIGINT REFERENCES TEST.DOC (ID)
);

CREATE TABLE TEST.STOP_WORD (
  ID   SERIAL PRIMARY KEY,
  WORD VARCHAR NOT NULL
);
