CREATE TABLE FINANCIAL_INDICATOR (
  ID   SERIAL PRIMARY KEY,
  NAME VARCHAR
);

CREATE TABLE METRICS (
  ID                     SERIAL PRIMARY KEY,
  NAME                   VARCHAR,
  FINANCIAL_INDICATOR_ID BIGINT REFERENCES FINANCIAL_INDICATOR (ID),
  MAX_VALUE              DECIMAL,
  MIN_VALUE              DECIMAL
);

CREATE TABLE METRICS_AUDIT (
  METRICS_ID    BIGINT,
  OLD_MAX_VALUE DECIMAL,
  NEW_MAX_VALUE DECIMAL,
  OLD_MIN_VALUE DECIMAL,
  NEW_MIN_VALUE DECIMAL,
  USER_LOGIN    VARCHAR,
  DATE          BIGINT,
  PRIMARY KEY (METRICS_ID, USER_LOGIN, DATE)
);

INSERT INTO FINANCIAL_INDICATOR (NAME) VALUES ('GOLD');
INSERT INTO FINANCIAL_INDICATOR (NAME) VALUES ('TESLA SHARE');

INSERT INTO METRICS (NAME, FINANCIAL_INDICATOR_ID, MAX_VALUE, MIN_VALUE)
VALUES ('PRICE IN RUBLES', 1, 3000 :: DECIMAL, 2500 :: DECIMAL);
INSERT INTO METRICS (NAME, FINANCIAL_INDICATOR_ID, MAX_VALUE, MIN_VALUE)
VALUES ('PRICE IN DOLLARS', 1, 50 :: DECIMAL, 42.0 :: DECIMAL);
INSERT INTO METRICS (NAME, FINANCIAL_INDICATOR_ID, MAX_VALUE, MIN_VALUE)
VALUES ('PRICE IN RUBLES', 2, 300.0 :: DECIMAL, 250.0 :: DECIMAL);
INSERT INTO METRICS (NAME, FINANCIAL_INDICATOR_ID, MAX_VALUE, MIN_VALUE)
VALUES ('PRICE IN DOLLARS', 2, 5.0 :: DECIMAL, 4.2 :: DECIMAL);


CREATE TABLE METRICS_DEPENDENCE (
  METRICS_ID           BIGINT REFERENCES METRICS,
  DEPENDENT_METRICS_ID BIGINT REFERENCES METRICS,
  KOEFFICIENT          DECIMAL,
  OPERAND              VARCHAR(1),
  PRIMARY KEY (METRICS_ID, DEPENDENT_METRICS_ID)
);